Repository prnb22/webshop-demo-cloud, pull requests merged in 2025-02, with the labels that each got.

#15 Implemented product list api
  backend/src/main/java/com/cloud/webshop/config/SecurityConfig.java
  backend/src/main/java/com/cloud/webshop/controller/ProductController.java
  backend/src/main/java/com/cloud/webshop/model/Product.java
  backend/src/main/java/com/cloud/webshop/repository/ProductRepository.java
  backend/src/main/java/com/cloud/webshop/response/ApiResponse.java
  backend/src/main/java/com/cloud/webshop/response/ProductResponse.java
  backend/src/main/java/com/cloud/webshop/service/ProductService.java
  backend/src/main/java/com/cloud/webshop/service/impl/ProductServiceImpl.java
Labels: new feature

#22 reverting securityconfig
  backend/src/main/java/com/cloud/webshop/config/SecurityConfig.java
Labels: bug

#36 Create Cart, Cart List, Create an Order
  backend/README.md
  backend/src/main/java/com/cloud/webshop/config/SecurityConfig.java
  backend/src/main/java/com/cloud/webshop/controller/CartController.java
  backend/src/main/java/com/cloud/webshop/controller/OrderController.java
  backend/src/main/java/com/cloud/webshop/controller/ProductController.java
  backend/src/main/java/com/cloud/webshop/model/Cart.java
  backend/src/main/java/com/cloud/webshop/model/Order.java
  backend/src/main/java/com/cloud/webshop/model/OrderProduct.java
  backend/src/main/java/com/cloud/webshop/model/OrderProductId.java
  backend/src/main/java/com/cloud/webshop/model/Product.java
  backend/src/main/java/com/cloud/webshop/model/Supplier.java
  backend/src/main/java/com/cloud/webshop/repository/CartRepository.java
  backend/src/main/java/com/cloud/webshop/repository/OrderProductRepository.java
  backend/src/main/java/com/cloud/webshop/repository/OrderRepository.java
  backend/src/main/java/com/cloud/webshop/request/AddToCartRequest.java
  backend/src/main/java/com/cloud/webshop/response/ApiResponse.java
  backend/src/main/java/com/cloud/webshop/response/CartItemResponse.java
  backend/src/main/java/com/cloud/webshop/response/CartListResponse.java
  backend/src/main/java/com/cloud/webshop/response/ProductResponse.java
  backend/src/main/java/com/cloud/webshop/service/CartService.java
  backend/src/main/java/com/cloud/webshop/service/OrderService.java
  backend/src/main/java/com/cloud/webshop/service/ProductService.java
  backend/src/main/java/com/cloud/webshop/service/impl/CartServiceImpl.java
  backend/src/main/java/com/cloud/webshop/service/impl/OrderServiceImpl.java
  backend/src/main/java/com/cloud/webshop/service/impl/ProductServiceImpl.java
Labels: new feature

#39 [UI] Implemented add cart functionality
  dummy-backend/data/products.json
  dummy-backend/server.js
  frontend/src/app/app.component.ts
  frontend/src/app/features/products/product-detail/product-detail.component.html
  frontend/src/app/features/products/product-detail/product-detail.component.ts
  frontend/src/app/services/app-state.service.ts
  frontend/src/app/services/rest.service.ts
  frontend/src/app/shared/components/nav/nav.component.css
  frontend/src/app/shared/components/nav/nav.component.html
  frontend/src/app/shared/components/nav/nav.component.ts
  frontend/src/environments/environment.ts
Labels: new feature

#42 [Backend] Add CORS configuration for API endpoints
  backend/src/main/java/com/cloud/webshop/config/WebConfig.java
Labels: enhancement

#46 [UI] Add new product page
  frontend/src/app/app.routes.ts
  frontend/src/app/features/products/handle-product/handle-product.component.ts
  frontend/src/app/features/products/product-add/add-product.component.css
  frontend/src/app/features/products/product-add/add-product.component.html
  frontend/src/app/features/products/product-add/add-product.component.ts
  frontend/src/app/shared/components/header/navigation-items/navigation-items.component.html
  frontend/src/app/shared/utils/lazy-loading.utils.ts
Labels: new feature

#44 [UI] Implemented cart-list and integrated with backend #43
  frontend/src/app/features/cart/cart-item/cart-item.component.html
  frontend/src/app/features/cart/cart-item/cart-item.component.ts
  frontend/src/app/features/cart/cart.component.ts
  frontend/src/app/features/products/product-detail/product-detail.component.ts
  frontend/src/app/model/interfaces/base-response.interface.ts
  frontend/src/app/model/interfaces/cart-item.interface.ts
  frontend/src/app/model/interfaces/shopping-cart.interface.ts
  frontend/src/app/services/app-state.service.ts
  frontend/src/app/services/cart.service.ts
  frontend/src/app/services/rest.service.ts
Labels: new feature

#49 [UI] Implemented product update page
  frontend/src/app/features/products/product-add/add-product.component.html
  frontend/src/app/features/products/product-add/add-product.component.ts
  frontend/src/app/features/products/product-detail/product-detail.component.css
  frontend/src/app/features/products/product-detail/product-detail.component.html
  frontend/src/app/features/products/product-detail/product-detail.component.ts
Labels: new feature

#52 [UI] Add Manage Inventory item in the nav bar
  frontend/src/app/shared/components/header/navigation-items/navigation-items.component.css
  frontend/src/app/shared/components/header/navigation-items/navigation-items.component.html
  frontend/src/app/shared/components/header/navigation-items/navigation-items.component.ts
Labels: enhancement, new feature

#53 Inventory and Supplier APIs, modified creating order
  backend/src/main/java/com/cloud/webshop/controller/InventoryController.java
  backend/src/main/java/com/cloud/webshop/controller/ProductController.java
  backend/src/main/java/com/cloud/webshop/controller/SupplierController.java
  backend/src/main/java/com/cloud/webshop/model/Order.java
  backend/src/main/java/com/cloud/webshop/model/Product.java
  backend/src/main/java/com/cloud/webshop/model/Supplier.java
  backend/src/main/java/com/cloud/webshop/repository/InventoryRepository.java
  backend/src/main/java/com/cloud/webshop/repository/ProductRepository.java
  backend/src/main/java/com/cloud/webshop/repository/SupplierRepository.java
  backend/src/main/java/com/cloud/webshop/request/InventoryRequest.java
  backend/src/main/java/com/cloud/webshop/response/InventoryResponse.java
  backend/src/main/java/com/cloud/webshop/response/ProductResponse.java
  backend/src/main/java/com/cloud/webshop/response/SupplierResponse.java
  backend/src/main/java/com/cloud/webshop/service/InventoryService.java
  backend/src/main/java/com/cloud/webshop/service/ProductService.java
  backend/src/main/java/com/cloud/webshop/service/SupplierService.java
  backend/src/main/java/com/cloud/webshop/service/impl/InventoryServiceImpl.java
  backend/src/main/java/com/cloud/webshop/service/impl/OrderServiceImpl.java
  backend/src/main/java/com/cloud/webshop/service/impl/ProductServiceImpl.java
  backend/src/main/java/com/cloud/webshop/service/impl/SupplierServiceImpl.java
Labels: enhancement, new feature

#58 [UI] implemented search functionality in product list
  frontend/src/app/features/products/product-list/product-list.component.css
  frontend/src/app/features/products/product-list/product-list.component.html
  frontend/src/app/features/products/product-list/product-list.component.ts
  frontend/src/app/services/guard.service.ts
  frontend/src/app/services/rest.service.ts
  frontend/src/index.html
Labels: new feature

#59 [UI] Implement add supplier page with network call
  frontend/src/app/app.routes.ts
  frontend/src/app/enum/route.enum.ts
  frontend/src/app/features/supplier/supplier-add/add-supplier.component.css
  frontend/src/app/features/supplier/supplier-add/add-supplier.component.html
  frontend/src/app/features/supplier/supplier-add/add-supplier.component.ts
  frontend/src/app/model/interfaces/supplier.interface.ts
  frontend/src/app/services/supplier.service.ts
  frontend/src/app/shared/components/header/navigation-items/navigation-items.component.html
  frontend/src/app/shared/utils/lazy-loading.utils.ts
Labels: new feature

#61 Modify product list with custom search, individual product list API
  backend/src/main/java/com/cloud/webshop/controller/ProductController.java
  backend/src/main/java/com/cloud/webshop/response/ProductNameResponse.java
  backend/src/main/java/com/cloud/webshop/response/ProductResponse.java
  backend/src/main/java/com/cloud/webshop/service/ProductService.java
  backend/src/main/java/com/cloud/webshop/service/impl/ProductServiceImpl.java
Labels: new feature

#66 Fixed pagination in product list, search and added supply list in inventory add form
  frontend/src/app/features/inventory/add-inventory/add-inventory.component.css
  frontend/src/app/features/inventory/add-inventory/add-inventory.component.html
  frontend/src/app/features/inventory/add-inventory/add-inventory.component.ts
  frontend/src/app/features/products/product-list/product-list.component.html
  frontend/src/app/features/products/product-list/product-list.component.ts
  frontend/src/app/model/interfaces/product.interface.ts
  frontend/src/app/model/interfaces/supplier.interface.ts
  frontend/src/app/services/app-state.service.ts
  frontend/src/app/services/guard.service.ts
  frontend/src/app/services/rest.service.ts
  frontend/src/app/shared/components/header/navigation-items/navigation-items.component.html
  frontend/src/app/shared/components/header/navigation-items/navigation-items.component.ts
Labels: bug, enhancement, new feature

#69 [UI] Show order history in ui
  frontend/src/app/features/orders/manage-order/manage-orders.component.css
  frontend/src/app/features/orders/manage-order/manage-orders.component.html
  frontend/src/app/features/orders/manage-order/manage-orders.component.ts
  frontend/src/app/model/interfaces/order.interface.ts
  frontend/src/app/services/order.service.ts
Labels: enhancement, new feature

#67 [UI] Implemented update and delete inventory functionality
  frontend/angular.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/features/inventory/add-inventory/add-inventory.component.css
  frontend/src/app/features/inventory/add-inventory/add-inventory.component.html
  frontend/src/app/features/inventory/add-inventory/add-inventory.component.ts
  frontend/src/app/features/products/product-detail/product-detail.component.css
  frontend/src/app/features/products/product-detail/product-detail.component.html
  frontend/src/app/features/products/product-detail/product-detail.component.ts
  frontend/src/app/features/products/product-list/product-list.component.ts
  frontend/src/app/model/interfaces/inventory.interface.ts
  frontend/src/app/model/interfaces/product.interface.ts
  frontend/src/app/model/product.model.ts
  frontend/src/app/services/guard.service.ts
  frontend/src/app/services/inventory.service.ts
  frontend/src/app/services/rest.service.ts
  frontend/src/app/shared/components/confirm-dialog/confirm-dialog.component.ts
  frontend/src/index.html
  frontend/src/main.ts
  frontend/src/styles.css
Labels: new feature

#70 Dockerise the Frontend
  frontend/.dockerignore
  frontend/Dockerfile
  frontend/nginx.conf
  frontend/src/app/features/products/product-add/add-product.component.html
  frontend/src/app/shared/components/header/navigation-items/navigation-items.component.html
Labels: new feature
