Repository prnb22/webshop-demo-cloud, pull requests merged in 2025-03, with the labels that each got.

#82 fix cart count in product page
  frontend/src/app/app.component.ts
  frontend/src/app/features/products/product-list/product-list.component.ts
Labels: bug

#85 [Bugfix] Remove duplicate cartId from CartItem model
  frontend/src/app/model/interfaces/cart-item.interface.ts
Labels: bug

#89 fix pagination without arrow and add product integration
  frontend/src/app/features/products/pagination/pagination.component.html
  frontend/src/app/features/products/pagination/pagination.component.ts
  frontend/src/app/features/products/product-add/add-product.component.css
  frontend/src/app/features/products/product-add/add-product.component.html
  frontend/src/app/features/products/product-add/add-product.component.ts
  frontend/src/app/features/products/product-detail/product-detail.component.css
  frontend/src/app/features/products/product-detail/product-detail.component.html
  frontend/src/app/features/products/product-detail/product-detail.component.ts
  frontend/src/app/features/products/product-list/product-list.component.ts
  frontend/src/app/model/product.model.ts
  frontend/src/app/services/app-state.service.ts
  frontend/src/app/services/product.service.ts
  frontend/src/app/shared/components/header/navigation-items/navigation-items.component.ts
  frontend/src/app/shared/utils/pagination.utils.ts
Labels: bug, enhancement

#92 Fix some known issues with proper validation
  frontend/src/app/features/cart/cart.component.css
  frontend/src/app/features/cart/cart.component.html
  frontend/src/app/features/orders/manage-order/manage-orders.component.css
  frontend/src/app/features/orders/manage-order/manage-orders.component.html
  frontend/src/app/features/products/product-detail/product-detail.component.css
  frontend/src/app/features/products/product-detail/product-detail.component.html
  frontend/src/app/shared/components/header/header.component.css
  frontend/src/app/shared/components/icons/back-arrow-icon/back-arrow-icon.component.ts
Labels: bug, enhancement

#94 price range filter in product list
  frontend/src/app/features/products/product-list/product-list.component.ts
  frontend/src/app/services/guard.service.ts
Labels: new feature

#96 Write CI/CD Pipeline
  .github/workflows/deploy.yml
Labels: new feature

#98 [Backend] Implement low stock warning mail
  backend/src/main/java/com/cloud/webshop/WebshopApplication.java
  backend/src/main/java/com/cloud/webshop/repository/InventoryRepository.java
  backend/src/main/java/com/cloud/webshop/service/InventoryMonitoringService.java
  backend/src/main/resources/templates/low-stock-alert.html
Labels: new feature

#99 CI/CD pipeline, make both frontend and backend https
  backend/docker-compose.yml
  backend/src/main/java/com/cloud/webshop/config/SecurityConfig.java
  backend/src/main/resources/application.yml
  backend/target/classes/application.yml
  frontend/Dockerfile
  frontend/docker-compose.yml
  frontend/nginx.conf
  frontend/src/app/features/cart/cart.component.ts
  frontend/src/environments/env.ts
  frontend/src/environments/environment.prod.ts
  frontend/src/environments/environment.ts
Labels: bug, new feature
